services:
  operaton:
    build: .
    container_name: dev-operaton
    restart: unless-stopped
    ports:
      - "8180:8085"
    networks:
      - dev-shared

networks:
  dev-shared:
    external: true
