spring:
  application:
    name: operaton-dev
  datasource:
    url: jdbc:postgresql://postgres:5432/operaton
    username: operaton
    password: operaton
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
    webapp:
      header-security:
        content-security-policy-value: "base-uri 'self';script-src 'strict-dynamic' 'unsafe-eval' https: 'self' 'unsafe-inline';style-src 'unsafe-inline' 'self';default-src 'self';img-src 'self' data:;block-all-mixed-content;form-action 'self';frame-ancestors 'self' http://192.168.0.10:8084;object-src 'none'"
