spring:
  application:
    name: operaton-dev
  datasource:
    url: jdbc:postgresql://postgres:5432/operaton
    username: operaton
    password: operaton
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

operaton:
  bpm:
    admin-user:
      id: demo
      password: demo
      first-name: Demo
    filter:
      create: All tasks
