services:
  appsmith:
    image: appsmith/appsmith-ce:latest
    container_name: dev-appsmith
    restart: unless-stopped
    ports:
      - "8084:80"
    environment:
      - APPSMITH_RATE_LIMIT=1000
    volumes:
      - ./stacks:/appsmith-stacks
